### ISSUE TITLE
Cordova 9.0.0 issue...

### ISSUE THREAD

**Issue by yoginm** [tgardner/cordova-plugin-platform-replace#1]
The plugin does not work with cordova 9.0.0.
requireCordovaModule is no longer allowed... 
Getting error: CordovaError: Using "requireCordovaModule" to load non-cordova module "fs" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.

Following code needs to be changed...
    var fs = ctx.requireCordovaModule('fs'),
        path = ctx.requireCordovaModule('path'),
        q = ctx.requireCordovaModule('q'),
        xml = ctx.requireCordovaModule('cordova-common').xmlHelpers;

to 

var fs = require('fs'),
path = require('path'),
q = require('q'),
xml = require('cordova-common').xmlHelpers;

and fs has to be added as the project dev dependencies.

**Comment by tgardner** [comment]
No problem, updated. Thanks for reporting!
